### ISSUE TITLE
Synchronisation error

### ISSUE THREAD

**Issue by adamshand** [acez/bookmark-companion#3] opened 2022-12-11 21:16 UTC
Hello from Reddit :-)

I installed your app and am having a play, thanks!  

I've entered my URL and token and now get a "Synchronisation error.  Please check your URL and your Token in the configuration dialog" error message.

Token is working with browser plugins, so I don't think there's anything wrong there.  Linkding is the latest docker container.

 I'm not getting any errors in the Linkding logs.

The weird thing is that it seems to be partially working.  I can add bookmarks and tags via your app, but I can't see any of my bookmarks (except the bookmark I created via the app).  

I know the app is very early days. Do you want reports of UI bugs, or is that just noise at this point?

**Comment by acez** [comment] 2022-12-11 23:01
Hey, thank you for your feedback. Very much appreciated.

Some question so I can try to reproduce the issue:
- Can you see the request in the logs of linkding?
- Does your installation of linkding run directly within "<domain>/" on your domain or do you run it under a path like "<domain>/linkding"?
- Did you add a / at the end of your URL? If not, can you please try?
- Do you have a valid SSL certificate?

**Comment by sebw** [comment] 2022-12-11 23:24
Same problem here. 

Linkding has its own domain. No sub path. 

Tried both with and without trailing slash. 

For what it's worth my instance is behind a cloudflare tunnel with browser security check disabled.

**Comment by adamshand** [comment] 2022-12-12 00:45
- Yes, I can see the requests hit the linkding logs (no errors though).  The below log snippet is what I get when I pull down in the app to refresh bookmarks.
- It's on its own sub-domain at / (no sub-path)
- I have a / on the end of the URL (tried removing the / and it didn't make any difference)
- Yes, valid SSL certificate. Let's Encrypt via Caddy (on local network) and Cloudflare (via internet).  Same error either way I try and access.
- Happy to provide a Linkding account if that's useful for debugging.

```
linkding    | [pid: 17|app: 0|req: 1/1] 172.30.0.66 () {38 vars in 565 bytes} [Mon Dec 12 00:41:20 2022] GET /api/tags/ => generated 6972 bytes in 87 msecs (HTTP/1.1 200) 9 headers in 289 bytes (1 switches on core 0)
linkding    | [pid: 17|app: 0|req: 2/2] 172.30.0.66 () {38 vars in 606 bytes} [Mon Dec 12 00:41:20 2022] GET /api/tags/?limit=100&offset=100 => generated 7202 bytes in 10 msecs (HTTP/1.1 200) 9 headers in 289 bytes (1 switches on core 1)
linkding    | [pid: 17|app: 0|req: 3/3] 172.30.0.66 () {38 vars in 606 bytes} [Mon Dec 12 00:41:20 2022] GET /api/tags/?limit=100&offset=200 => generated 7198 bytes in 14 msecs (HTTP/1.1 200) 9 headers in 289 bytes (1 switches on core 0)
linkding    | [pid: 17|app: 0|req: 4/4] 172.30.0.66 () {38 vars in 606 bytes} [Mon Dec 12 00:41:20 2022] GET /api/tags/?limit=100&offset=300 => generated 7210 bytes in 9 msecs (HTTP/1.1 200) 9 headers in 289 bytes (1 switches on core 1)
linkding    | [pid: 17|app: 0|req: 5/5] 172.30.0.66 () {38 vars in 606 bytes} [Mon Dec 12 00:41:20 2022] GET /api/tags/?limit=100&offset=400 => generated 7173 bytes in 9 msecs (HTTP/1.1 200) 9 headers in 289 bytes (1 switches on core 0)
linkding    | [pid: 17|app: 0|req: 6/6] 172.30.0.66 () {38 vars in 606 bytes} [Mon Dec 12 00:41:20 2022] GET /api/tags/?limit=100&offset=500 => generated 7253 bytes in 10 msecs (HTTP/1.1 200) 9 headers in 289 bytes (1 switches on core 1)
linkding    | [pid: 17|app: 0|req: 7/7] 172.30.0.66 () {38 vars in 606 bytes} [Mon Dec 12 00:41:20 2022] GET /api/tags/?limit=100&offset=600 => generated 7225 bytes in 10 msecs (HTTP/1.1 200) 9 headers in 289 bytes (1 switches on core 0)
linkding    | [pid: 17|app: 0|req: 8/8] 172.30.0.66 () {38 vars in 606 bytes} [Mon Dec 12 00:41:20 2022] GET /api/tags/?limit=100&offset=700 => generated 3901 bytes in 8 msecs (HTTP/1.1 200) 9 headers in 289 bytes (1 switches on core 1)
linkding    | [pid: 15|app: 0|req: 1/9] 172.30.0.66 () {38 vars in 575 bytes} [Mon Dec 12 00:41:20 2022] GET /api/bookmarks/ => generated 37220 bytes in 140 msecs (HTTP/1.1 200) 9 headers in 290 bytes (1 switches on core 0)
```

**Comment by adamshand** [comment] 2022-12-12 00:49
Just tried deleting the app and re-configuring and same thing.

**Comment by acez** [comment] 2022-12-12 00:54
That's strange - I just tried it with my local installation and couldn't reproduce the issue. Not exactly sure what impact the CloudFlare tunnel has on that.
I added some additional error information for all API requests in commit bbc88c8886e4e70e5848c4004a79fb5cbabb94d0 so maybe we can get a clue what exactly is going wrong here.

I have uploaded a version to Apple Testflight and share the Link for it to test as soon as it is reviewed by Apple and ready to test.

@adamshand  If that brings no clue it would be great to get test instance for debugging. Thank you very much for that offer 😄

**Comment by acez** [comment] 2022-12-12 01:54
Some additional things for debugging in the meantime while waiting for testflight (if you have curl and jq installed):

Linkding API returns the next URL for paging in the response. Can you please check if the URL returned there makes sense (and is ideally the same as the request but only with limit and offset as additional parameters)?
You can test it with:
`curl --request GET --url https://<your-domain>/api/bookmarks/ --header 'Authorization: Token <your-token>' | jq ".next"`

Also can you maybe check if there are any bookmarks in the response:
`curl --request GET --url https://<your-domain>/api/bookmarks/ --header 'Authorization: Token <your-token>' | jq ".count"`

**Comment by adamshand** [comment] 2022-12-12 02:21
```sh
$ curl --request GET --url https://ld.example.nz/api/bookmarks/ --header 'Authorization: Token xxx' |  jq ".next"
"https://ld.haume.nz/api/bookmarks/?limit=100&offset=100"

$ curl --request GET --url https://ld.example.nz/api/bookmarks/ --header 'Authorization: Token xxx' |  jq ".count"
2240
```

**Comment by bachya** [comment] 2022-12-12 03:39
Experiencing the same issue (also behind Cloudflare). Happy to test once the TestFlight build is ready.

**Comment by acez** [comment] 2022-12-12 12:22
I have added additional debug messages in 6f83d49cc7b8054af875d148228dc7e37b7e473d - that will be part of next Testflight version. (Still waiting for Review of the last one..)

I still can't reproduce the issue locally. I tried with https://try.cloudflare.com/ 
`docker run -d --network linkding-net cloudflare/cloudflared:latest tunnel --url http://linkding:9090`
but still it works for me. Do you have any hint if I miss any parameter here to be able to reproduce it?

**Comment by acez** [comment] 2022-12-12 14:31
I was able to produce a json decoding error by manually saving a bookmark via the admin UI.

Can you please check the date format of the linkding api:
`curl --request GET --url https://<your-domain>/api/bookmarks/ --header 'Authorization: Token <token>'  | jq ".results[0].date_added"`

After adding the bookmark via the UI for me it looks like this:
```
$ curl --request GET --url https://<domain>/api/bookmarks/ --header 'Authorization: Token <token>'  | jq ".results[0].date_added"
"2022-12-12T15:25:02.683504+01:00"
```

After just opening and saving the bookmark (without changing anything) in the admin UI it looks like this:
```
$ curl --request GET --url https://<domain>/api/bookmarks/ --header 'Authorization: Token <token>'  | jq ".results[0].date_added"
"2022-12-12T15:25:02+01:00"
```

Would appreciate if somebody can confirm the second time format.

Edit: Workaround added in 5b27a698d57527b481b0d4aa31191548f6fd32c5

**Comment by bachya** [comment] 2022-12-12 15:38
Here's the datetime format my returns for the second format: `"2022-12-11T02:55:12.037644Z"`

**Comment by adamshand** [comment] 2022-12-12 20:22
I don't think it's Cloudflare.  I have the same problem when accessing Linkding directly through Caddy.

**Comment by adamshand** [comment] 2022-12-12 20:37
```sh 
$ curl --request GET --url https://ld.example.nz/api/bookmarks/ --header 'Authorization: Token xxx' |  jq ".results[0]"
{
  "id": 2256,
  "url": "https://github.com/acez/bookmark-companion/issues/3",
  "title": "",
  "description": "",
  "website_title": "Synchronisation error · Issue #3 · acez/bookmark-companion · GitHub",
  "website_description": "Hello from Reddit :-) I installed your app and am having a play, thanks! I've entered my URL and token and now get a \"Synchronisation error. Please check your URL and your Token in the configuration dialog\" error message. Token is workin...",
  "is_archived": false,
  "unread": false,
  "shared": false,
  "tag_names": [
    "test"
  ],
  "date_added": "2022-12-12T20:35:01.578360Z",
  "date_modified": "2022-12-12T20:35:01.578368Z"
}
```

**Comment by acez** [comment] 2022-12-12 20:48
Thank you very much for your input. My best guess currently is the issue with different datetime strings in the API.  At least that's how I was able to reproduce the issue that tags are synced, newly created bookmarks also but existing bookmarks are not synced to the device.

Let's hope Apple approves the Testflight version fast to test it. I uploaded a version with the fix in 5b27a698d57527b481b0d4aa31191548f6fd32c5 to Testflight today.

Maybe it's an older bookmark that causes that issue?
A different approach for checking would by directly via the sqlite database.
```
$ sqlite3 db.sqlite3
sqlite> select distinct length(date_added) from bookmarks_bookmark;
19
26
```

That's what happens when I create two bookmarks and save one of them with django admin (without changing anything). So seems like django admin saves the datetimes in a different format that the webview does.

**Comment by adamshand** [comment] 2022-12-12 21:10
```sh 
$ sqlite3 app/db.sqlite3
sqlite> select distinct length(date_added) from bookmarks_bookmark;
length(date_added)
------------------
26
19
```

**Comment by acez** [comment] 2022-12-12 21:17
The version with latest fixes is now available for test on Testflight.
You should be able to get it via: https://testflight.apple.com/join/jRjbXy6B

Hope it fixes the issues with synchronization or at least gives some more hints about what happens. 😃

**Comment by bachya** [comment] 2022-12-12 22:35
> The version with latest fixes is now available for test on Testflight. You should be able to get it via: https://testflight.apple.com/join/jRjbXy6B
> 
> Hope it fixes the issues with synchronization or at least gives some more hints about what happens. 😃

Confirmed: this test build fixes the issue, and all my bookmarks are syncing. 🥳

**Comment by adamshand** [comment] 2022-12-13 00:16
Yep, works for me to now.  Thanks!

**Comment by acez** [comment] 2022-12-13 12:07
Great to hear! **Thank you very much** for help and testing everyone!

I added the latest Testflight Version for AppStore Review and will close this issue as soon as it is released.

**Comment by sebw** [comment] 2022-12-13 17:28
I guess this can be closed :) Fixed on my end as well!

**Comment by acez** [comment] 2022-12-14 10:26
Latest Version is on the AppStore. Thanks again.

**Closed as completed by acez** 2022-12-14 10:26 UTC
